[package]
name = "rustsql"
version = "0.1.0"
authors = ["Madushan Nishantha <j.l.madushan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
parameterized = "0.1.1"